# Build settings
markdown: kramdown
highlighter: rouge
gems: [rouge, kramdown]

sass:
  style: compressed
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  blanklines: false
  profile: false
  startings: [html, head, body]
